# Generated by Django 6.0 on 2026-03-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Art Name')),
                ('content', models.TextField(verbose_name='Art Content')),
                ('input', models.TextField(verbose_name='Art Input')),
                ('date', models.DateTimeField(verbose_name='Art Date')),
            ],
        ),
    ]
